server:
  host: "0.0.0.0"
  port: 8080

routes:
  - path: "users"
    upstream: "http://host.docker.internal:8081"
    timeout_ms: 5000
  - path: "payments"
    upstream: "http://mock-payment-service:8082"
    timeout_ms: 10000
